BEGIN;

DROP TABLE IF EXISTS public.book;
CREATE TABLE IF NOT EXISTS public.book
(
	id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer NOT NULL,
    id_schedule integer NOT NULL,
    id_seats integer[] NOT NULL,
    id_food_drink integer[] NOT NULL,
	start_time time without time zone NOT NULL,
    purchase_date date NOT NULL,
    CONSTRAINT book_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.blacklist;
CREATE TABLE IF NOT EXISTS public.blacklist
(
    id_user integer NOT NULL,
    CONSTRAINT blacklist_pkey PRIMARY KEY (id_user)
);

DROP TABLE IF EXISTS public.cinemas;
CREATE TABLE IF NOT EXISTS public.cinemas
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    province character varying COLLATE pg_catalog."default" NOT NULL,
    location character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cinemas_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.food_drink;
CREATE TABLE IF NOT EXISTS public.food_drink
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default" NOT NULL,
    price real NOT NULL,
	CONSTRAINT food_drink_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.genres;
CREATE TABLE IF NOT EXISTS public.genres
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
	CONSTRAINT genres_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.movies;
CREATE TABLE IF NOT EXISTS public.movies
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying COLLATE pg_catalog."default" NOT NULL,
    release_date date NOT NULL,
    url_poster character varying COLLATE pg_catalog."default" NOT NULL,
    director character varying COLLATE pg_catalog."default" NOT NULL,
    actors character varying COLLATE pg_catalog."default" NOT NULL,
    genres integer[] NOT NULL,
    duration time without time zone NOT NULL,
    age integer NOT NULL,
    overview text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT movies_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.rooms;
CREATE TABLE IF NOT EXISTS public.rooms
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_cinemas integer[] NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
	description character varying COLLATE pg_catalog."default" NOT NULL,
	surcharge real NOT NULL,
    CONSTRAINT rooms_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.schedule;
CREATE TABLE IF NOT EXISTS public.schedule
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_movie integer NOT NULL,
	id_cinema integer NOT NULL,
    id_room integer NOT NULL,
    date date NOT NULL,
    "time" time without time zone[] NOT NULL,
    CONSTRAINT schedule_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.seats;
CREATE TABLE IF NOT EXISTS public.seats
(
    id_seat integer NOT NULL,
    id_schedule integer NOT NULL,
    "time" time without time zone NOT NULL,
    status integer NOT NULL,
    CONSTRAINT seats_pkey PRIMARY KEY (id_seat, id_schedule, time)
);

DROP TABLE IF EXISTS public.shifts;
CREATE TABLE IF NOT EXISTS public.shifts
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_cinema integer NOT NULL,
    day character varying NOT NULL,
    time_start time without time zone NOT NULL,
    time_end time without time zone NOT NULL,
	id_staffs integer[],
    CONSTRAINT shifts_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.staff;
CREATE TABLE IF NOT EXISTS public.staff
(
    id_user integer NOT NULL,
    id_shifts integer[],
    CONSTRAINT staff_pkey PRIMARY KEY (id_user)
);

DROP TABLE IF EXISTS public.users;
CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    phone character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    dob date NOT NULL,
    gender character varying COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


------ DROP ALL FUNCTIONS ------
DO
$do$
DECLARE
   _sql text;
BEGIN
   SELECT INTO _sql
          string_agg(format('DROP %s %s;'
                          , CASE prokind
                              WHEN 'f' THEN 'FUNCTION'
                              WHEN 'a' THEN 'AGGREGATE'
                              WHEN 'p' THEN 'PROCEDURE'
                              WHEN 'w' THEN 'FUNCTION'
                            END
                          , oid::regprocedure)
                   , E'\n')
   FROM   pg_proc
   WHERE  pronamespace = 'public'::regnamespace;

   IF _sql IS NOT NULL THEN
      EXECUTE _sql;
   END IF;
END
$do$;


------ About book ------
-- insert data sample
--INSERT INTO book (id_user, id_seats, id_schedule, id_food_drink, start_time, purchase_date)
--VALUES (1, ARRAY[26, 21, 6], 1, ARRAY[1, 18], '09:00:00', CURRENT_DATE);

-- get booking history
CREATE OR REPLACE FUNCTION get_booking_history(user_id integer)
RETURNS TABLE(id_book integer, cinema_name character varying, location character varying, purchase_date timestamp with time zone, title character varying, start_time time without time zone, end_time time without time zone, room_name character varying, seats text[], food_drink text[], total_price double precision) AS $$
BEGIN
	RETURN QUERY
	SELECT	_b.id AS id_book,
			_c.name AS cinema_name,
			_c.location,
			_b.purchase_date AT TIME ZONE 'UTC' AT TIME ZONE 'GMT+7' AS purchase_date,
			_m.title,
			_b.start_time,
			(_b.start_time + _m.duration::interval)::time AS end_time,
			_r.name AS room_name,
			ARRAY (	SELECT	chr(65 + (num - 1) / 20) || (num - 1) % 20 + 1
					FROM	unnest(_b.id_seats) as t(num)) AS seats,
			ARRAY (	SELECT name || ' (' || description || ')'
					FROM food_drink
					WHERE id = ANY(id_food_drink)) AS food_drink,
			(real_price(_s.date, _b.start_time, _u.dob, _r.id) * ARRAY_LENGTH(_b.id_seats, 1)	-- ticket's price
			 + (SELECT	COALESCE(SUM(element), 0)
				FROM	unnest(ARRAY (SELECT price
									  FROM food_drink
									  WHERE id = ANY(id_food_drink))
							  ) AS element)														-- food_drink's price
			)AS total_price
	FROM	book _b
			JOIN schedule _s ON _b.id_schedule = _s.id
			JOIN cinemas _c ON _s.id_cinema = _c.id
			JOIN movies _m ON _s.id_movie = _m.id 
			JOIN rooms _r ON _s.id_room = _r.id
			JOIN users _u ON _b.id_user = _u.id
	WHERE _u.id = user_id
	ORDER BY _b.id DESC;
END;
$$ LANGUAGE plpgsql;
-- SELECT * FROM get_booking_history(1);

CREATE OR REPLACE FUNCTION delete_history(f_id_book INTEGER)
RETURNS BOOLEAN AS $$
DECLARE
	f_date 			DATE;
	f_start_time	TIME WITHOUT TIME ZONE;
BEGIN
	SELECT	_s.date, _b.start_time INTO f_date, f_start_time
	FROM	book _b JOIN schedule _s ON _b.id_schedule = _s.id
	WHERE	_b.id = f_id_book;
	
	IF (f_date > CURRENT_DATE) THEN
		RETURN FALSE;
	ELSIF (f_date = CURRENT_DATE AND f_start_time > CURRENT_TIME) THEN
		RETURN FALSE;
	END IF;
	
	DELETE FROM book WHERE id = f_id_book;
	
	RETURN TRUE;
END;
$$ LANGUAGE plpgsql;
-- SELECT delete_history(35) as status

-- add an account to blacklist to test
-- INSERT INTO blacklist VALUES (1);

INSERT INTO cinemas (province, name, location)
VALUES	('Hồ Chí Minh',	'CGV Hùng Vương Plaza',				'Tầng 7 | Hùng Vương Plaza, 126 Hồng Bàng, Phường 12, Quận 5, TP. Hồ Chí Minh.'),
		('Hồ Chí Minh',	'CGV Vivo City',					'Lầu 5, Trung tâm thương mại SC VivoCity - 1058 Nguyễn Văn Linh, Quận 7'),
		('Hồ Chí Minh',	'CGV Menas Mall (CGV CT Plaza)',	'Tầng 10, TTTM Menas Mall, 60A Trường Sơn, P.2, Q. Tân Bình, TP.HCM, Việt Nam'),
		('Hồ Chí Minh',	'CGV Hoàng Văn Thụ',				'Tầng 1 và 2, Gala Center, số 415, Hoàng Văn Thụ, Phường 2, Quận Tân Bình, TPHCM'),
		('Hồ Chí Minh',	'CGV Sư Vạn Hạnh',					'Tầng 6, Vạn Hạnh Mall, 11 Sư Vạn Hạnh, Phường 12, Quận 10'),
		('Hồ Chí Minh',	'CGV Lý Chính Thắng',				'Tầng 3, 83 Lý Chính Thắng, Phường 8, Q.3, TP.HCM'),
		('Hồ Chí Minh','CGV Crescent Mall','Lầu 5, Crescent Mall Đại lộ Nguyễn Văn Linh, Phú Mỹ Hưng Quận 7 TP. Hồ Chí Minh'),
		('Hồ Chí Minh','CGV Pearl Plaza','Tầng 5, Pearl Plaza, 561A Điện Biên Phủ, P.25, Q.Bình Thạnh, TP.HCM'),
		('Hồ Chí Minh','CGV Pandora City','Lầu 3, Pandora City 1/1 Trường Chinh Quận Tân Phú TP. Hồ Chí Minh'),
		('Hồ Chí Minh','CGV Aeon Bình Tân','Tầng 3, Trung tâm thương mại Aeon Mall Bình Tân, Số 1 đường số 17A, khu phố 11, phường Bình Trị Đông B, quận Bình Tân, TPHCM'),
		('Hồ Chí Minh','CGV Vincom Center Landmark 81','Tầng B1 , TTTM Vincom Center Landmark 81, 772 Điện Biên Phủ, P.22, Q. Bình Thạnh, HCM'),
		('Hồ Chí Minh','CGV Thảo Điền Pearl','Tầng 2, Thảo Điền Mall, 12 Quốc Hương, Phường Thảo Điền, Quận 2, TP. Hồ Chí Minh'),
		('Hồ Chí Minh','CGV Liberty Citypoint','Tầng M - 1, khách sạn Liberty Center Saigon Citypoint, 59 - 61 Pasteur, Quận 1'),
		('Hồ Chí Minh','CGV Aeon Tân Phú','Lầu 3, Aeon Mall 30 Bờ Bao Tân Thắng, P. Sơn Kỳ Quận Tân Phú TP. Hồ Chí Minh'),
		('Hồ Chí Minh','CGV Saigonres Nguyễn Xí','Tầng 4-5, Toà nhà Vincom Saigonres, 188 Nguyễn Xí, P.26, Q.Bình Thạnh, TP. Hồ Chí Minh'),
		('Hồ Chí Minh','CGV Satra Củ Chi','Tầng 3, TTTM Satra Củ Chi, Số 1239, Tỉnh Lộ 8, Ấp Thạnh An, Xã Trung An, Huyện Củ Chi, TP.HCM'),
		('Hồ Chí Minh','CGV Vincom Thủ Đức','Tầng 5, TTTM Vincom Thủ Đức, 216 Võ Văn Ngân, Phường Bình Thọ, Quận Thủ Đức'),
		('Hồ Chí Minh','CGV Vincom Đồng Khởi','Tầng 3, TTTM Vincom Center Đồng Khởi, 72 Lê Thánh Tôn & 45A Lý Tự Trọng, Quận 1, TP.HCM'),
		('Hồ Chí Minh','CGV Vincom Gò Vấp','Tầng 5 TTTM Vincom Plaza Gò Vấp, 12 Phan Văn Trị, Phường 7, Quận Gò Vấp'),
		('Hồ Chí Minh','CGV Parkson Đồng Khởi','Tầng 5, số 35 bis-45, đường Lê Thánh Tôn, Phường Bến Nghé, Quận 1, Tp. Hồ Chí Minh, Việt Nam'),
		('Hồ Chí Minh','CGV Giga Mall Thủ Đức','Tầng 6 TTTM GIGAMALL, 240-242 Phạm Văn Đồng, P. Hiệp Bình Chánh, Q. Thủ Đức, TPHCM'),
		('Hà Nội','CGV Vincom Center Bà Triệu','Tầng 6, Toà nhà VinCom Center Hà Nội 191 đường Bà Triệu Quận Hai Bà Trưng Hà Nội'),
		('Hà Nội','CGV Mipec Tower','Tầng 5, MIPEC Tower 229 Tây Sơn Quận Đống Đa, Hà Nội'),
		('Hà Nội','CGV Hồ Gươm Plaza','Tầng 3, TTTM Hồ Gươm Plaza, 110 Trần Phú, Phường Mỗ Lao, Quận Hà Đông, Hà Nội'),
		('Hà Nội','CGV Aeon Long Biên','Tầng 4 - TTTM AEON Long Biên, Số 27 Cổ Linh, Quận Long Biên, Hà Nội'),
		('Hà Nội','CGV Vincom Nguyễn Chí Thanh','Số 54A Nguyễn Chí Thanh, Phường Láng Thượng, Quận Đống Đa, Hà Nội'),
		('Hà Nội','CGV Indochina Plaza Hà Nội','Tầng 4, Indochina Plaza Hà Nội, 241 Xuân Thủy, Q. Cầu Giấy, Hà Nội'),
		('Hà Nội','CGV Rice City','Tầng 2 và 4, Tòa nhà Trung - RICE CITY Linh Đàm, Phường Hoàng Liệt, Quận Hoàng Mai, Thành phố Hà Nội'),
		('Hà Nội','CGV Hà Nội Centerpoint','Tầng 5 TTTM Hà Nội Centerpoint, 27 Lê Văn Lương (Số 85 Lê Văn Lương cũ), Phường Nhân Chính, Quận Thanh Xuân, TP.Hà Nội'),
		('Hà Nội','CGV Vincom Royal City','Tầng B2- Khu R4, TTTM Vincom Mega Mall Royal City , 72A Nguyễn Trãi,Thanh Xuân, Hà Nội'),
		('Hà Nội','CGV Vincom Times City','Tầng B1, TTTM Vincom Mega Mall Times City, 458 Minh Khai, Hai Bà Trưng, Hà Nội'),
		('Hà Nội','CGV Vincom Long Biên','Tầng 5, TTTM Vincom Plaza Long Biên, khu đô thị Vinhomes Riverside, Phường Phúc Lợi, Quận Long Biên, Hà Nội'),
		('Hà Nội','CGV Mac Plaza (Machinco)','Tầng 7, Trung tâm thương mại Mac Plaza, 10 Trần Phú, Q, Hà Đông, Hanoi City'),
		('Hà Nội','CGV Trương Định Plaza','Tầng 5, 461 Trương Định, Hoàng Mai, Hà Nội'),
		('Hà Nội','CGV Tràng Tiền Plaza','Tầng 5 , TTTM Tràng Tiền Plaza 24 Hai Bà Trưng, Q.Hoàn Kiếm, Hà Nội '),
		('Hà Nội','CGV Sun Grand Thụy Khuê','Tầng 5.1 - 5.2, Sun Grand City Thuy Khue Residence, 69B Thụy Khuê, P. Thụy Khuê, Q. Tây Hồ, Hà Nội'),
		('Hà Nội','CGV Sun Grand Lương Yên','Tầng 5.1 - 5.2, Sun Grand City Thuy Khue Residence, 69B Thụy Khuê, P. Thụy Khuê, Q. Tây Hồ, Hà Nội'),
		('Hà Nội','CGV Vincom Bắc Từ Liêm','Tòa nhà 21B5, 234 Phạm Văn Đồng, Bắc Từ Liêm, Cổ Nhuế, Từ Liêm, Hà Nội'),
		('Hà Nội','CGV Vincom Metropolis Liễu Giai','29 Liễu Giai, quận Ba Đình, Hà Nội'),
		('Hà Nội','CGV Xuân Diệu','Tầng 2, Tòa nhà D’. Le Roi Soleil, số 59 Xuân Diệu, P. Quảng An, Q. Tây Hồ, Hà Nội'),
		('Hà Nội','CGV Vincom Sky Lake Phạm Hùng','Tầng 3 - TTTM Vincom Plaza Skylake, đường Phạm Hùng, P. Mỹ Đình 1, Q.Nam Từ Liêm, Hà Nội'),
		('Hà Nội','CGV Vincom Trần Duy Hưng','Tầng 5 - TTTM VINCOM CENTER TRẦN DUY HUNG, Đường Trần Duy Hưng, P. Trung Hòa, Q. Cầu Giấy, Hà Nội'),
		('Hà Nội','CGV Aeon Hà Đông','Tầng 3 & 4 – TTTM AEON MALL HÀ ĐÔNG, P. Dương Nội, Q. Hà Đông, Hà Nội'),
		('Hà Nội','CGV Vincom Ocean Park','Tầng 4, Trung Tâm Thương Mại Vincom Ocean Park, Huyện Gia Lâm, Hà Nội'),
		('Đà Nẵng','CGV Vĩnh Trung Plaza','255-257 đường Hùng Vương Quận Thanh Khê Tp. Đà Nẵng'),
		('Đà Nẵng','CGV Vincom Đà Nẵng','Tầng 4, TTTM Vincom Đà Nẵng, đường Ngô Quyền, P.An Hải Bắc, Q.Sơn Trà, TP. Đà Nẵng'),
		('Cần Thơ','CGV Sense City','Lầu 3, Sense City 1 Đại Lộ Hòa Bình Quận Ninh Kiều TP. Cần Thơ'),
		('Cần Thơ','CGV Vincom Xuân Khánh','Tầng 5, Tòa nhà 209, Đường 30/04, Phường Xuân Khánh, Quận Ninh Kiều, Tp. Cần Thơ'),
		('Cần Thơ','CGV Vincom Hùng Vương','02 Hùng Vương, Quận Ninh Kiều, TP. Cần Thơ'),
		('Đồng Nai','CGV Coopmart Biên Hòa','Tầng 3, Khu Siêu thị Co-op Mart 121 Phạm Văn Thuận, P.Tân Tiến Tp. Biên Hoà Tỉnh Đồng Nai'),
		('Đồng Nai','CGV Big C Đồng Nai','Siêu thị BigC Đồng Nai, Khu phố 1, Phường Long Bình Tân, TP. Biên Hòa, Đồng Nai'),
		('Hải Phòng','CGV Vincom Hải Phòng','Tầng 4, Vincom Plaza Imperia Hải Phòng, Khu đô thị Vinhomes Imperia Hải Phòng, Phường Thượng Lý, Quận Hồng Bàng, Thành phố Hải Phòng'),
		('Hải Phòng','CGV Aeon Mall Hải Phòng','Tầng 3 TTTM AEON MALL Hải Phòng Lê Chân, số 10 đường Võ Nguyên Giáp, Phường Kênh Dương, Quận Lê Chân, Thành phố Hải Phòng'),
		('Quảng Ninh','CGV Vincom Hạ Long','Tầng 4, TTTM Vincom Center Hạ Long, Khu Cột Đồng Hồ, P.Bạch Đằng, Hạ Long, Quảng Ninh'),
		('Quảng Ninh','CGV Vincom Móng Cái','Tầng 3 & tầng 4, Vincom Plaza Móng Cái, tổ hợp TTTM & và nhà ở liền kề ( Shophouse), Phường Trần Phú, Thành Phố Móng Cái, Tỉnh Quảng Ninh, Việt Nam'),
		('Quảng Ninh','CGV Vincom Cẩm Phả','Tầng 4, Vincom Cẩm Phả , P. Cẩm Bình, TP. Cẩm Phả, Tỉnh Quảng Ninh'),
		('Bà Rịa-Vũng Tàu','CGV Lam Sơn Square','Tầng 4, Lam Sơn Square 9 Lê Lợi Tp. Vũng Tàu'),
		('Bà Rịa-Vũng Tàu','CGV Lapen Center Vũng Tàu','Lapen Center Mall, Số 33A Đường 30/4, Phường 9, TP. Vũng Tàu, Bà Rịa - Vũng Tàu'),
		('Bình Định','CGV Kim Cúc Plaza','Tầng 3 | Kim Cúc Plaza (BigC Quy Nhơn) Khu Đô Thị Vũng Chua Phường Ghềnh Ráng Tp.Quy Nhơn, Bình Định'),
		('Bình Dương','CGV Bình Dương Square','Tầng 3 Bình Dương Square 1 Phú Lợi Phường Phú Lợi Tp.Thủ Dầu Một, Bình Dương'),
		('Bình Dương','CGV Aeon Canary','Tầng 2, trung tâm mua sắm AEON – Bình Dương Canary, Đại lộ Bình Dương, phường Bình Hòa, thị xã Thuân An, tỉnh Bình Dương'),
		('Đắk Lắk','CGV Buôn Mê Thuột','Tầng 4 TTTM Nguyễn Kim, số 01 Nguyễn Chí Thanh, phường Tân An, thành phố Buôn Ma Thuột, tỉnh Đak Lak'),
		('Trà Vinh','CGV Vincom Trà Vinh','Tầng 4, TTTM Vincom Plaza Trà Vinh, số 24 Đường Nguyễn Thị Minh Khai, Khóm 3, Phường 2, Thành phố Trà Vinh, Tỉnh Trà Vinh'),
		('Yên Bái','CGV Vincom Yên Bái','Tầng 4 – TTTM Vincom Yên Bái, Khu Bán Đảo Công Viên Yên Hòa, phường Nguyễn Thái Học, Thành phố Yên Bái'),
		('Vĩnh Long','CGV Vincom Vĩnh Long','Tầng 4, Trung Tâm Thương Mại Vincom Plaza Vĩnh Long. Số 55, đường Phạm Thái Bường, Phường 4, Thành phố Vĩnh Long'),
		('Kiên Giang','CGV Vincom Rạch Giá','Tầng 5, TTTM Vincom Plaza Kiên Giang, Lô A12, khu phố 1, đường Cô Bắc, phường Vĩnh Bảo, TP. Rạch Giá, Kiên Giang'),
		('Hậu Giang','CGV Vincom Vi Thanh','Tầng 4, TTTM Vincom Plaza Hậu Giang, số 1, Đường 3 tháng 2, Khu vực 3, Phường 5, TP.Vị Thanh, Hậu Giang'),
		('Hà Tĩnh','CGV Vincom Hà Tĩnh','Tầng 3, Trung tâm Thương mại Vincom Plaza Hà Tĩnh, góc ngã tư Hàm Nghi và Hà Huy Tập, Phường Hà Huy Tập, Thành phố Hà Tĩnh, Tỉnh Hà Tĩnh'),
		('Phú Yên','CGV Vincom Phú Yên','Tầng 4 - TTTM Vincom Plaza Tuy Hoà - Phú Yên, Góc Đông Bắc ngã tư đường Hùng Vương và đường Trần Phú, P.7, TP. Tuy Hoà, Tỉnh Phú Yên'),
		('Đồng Tháp','CGV Vincom Cao Lãnh','Tầng 5 – TTTM VINCOM CAO LÃNH, 02 Đường 30.04, Phường 01, TP. Cao Lãnh, Đồng Tháp'),
		('Hưng Yên','CGV Ecopark Hưng Yên','Tầng 1, Tòa Lake 1, Khu căn hộ Vịnh Thủy, Khu đô thị thương mại và du lịch Văn Giang, Xã Xuân Quan, Huyện Văn Giang, Tỉnh Hưng Yên'),
		('Khánh Hòa','CGV Big C Nha Trang','Tầng Trệt, TTTM Big C Nha Trang, Lô số 4, đường 19/5, Khu đô thị Vĩnh Điềm Trung, Xã Vĩnh Hiệp, TP. Nha Trang, Tỉnh Khánh Hòa'),
		('Kon Tum','CGV Vincom Kon Tum','Tầng 3 & 4, Vincom Plaza Kon Tum, 02 đường Phan Đình Phùng, P. Quyết Thắng, TP. Kon Tum, Tỉnh Kon Tum'),
		('Lạng Sơn','CGV Vincom Lạng Sơn','Tầng 3 , TTTM Vincom Lạng Sơn , Chi Lăng, TP. Lạng Sơn'),
		('Nghệ An','CGV Vinh Centre','Tầng 4 – TTTM Vinh Center, 69 Hồ Tùng Mậu, P. Trường Thi, TP. Vinh, Tỉnh Nghệ An, Việt Nam'),
		('Phú Thọ','CGV Happyland Việt Trì','Tầng 3, Tòa nhà Happyland Việt Trì, 1606A Đại Lộ Hùng Vương, P. Gia Cẩm, Việt Trì, Phú Thọ'),
		('Quảng Ngãi','CGV Vincom Quảng Ngãi','Nghĩa Chánh Nam, Quảng Ngãi'),
		('Sóc Trăng','CGV Vincom Sóc Trăng','Tầng 3 & 4, Vincom Sóc Trăng, đường Trần Hưng Đạo, P.2, TP. Sóc Trăng, Tỉnh Sóc Trăng'),
		('Sơn La','CGV Vincom Sơn La','Tầng 3 , TTTM Vincom Sơn La - Trường Chinh, P. Quyết Thắng, Sơn La'),
		('Tây Ninh','CGV Vincom Tây Ninh','54 Đặng Ngọc Chinh, Khu phố 1, Phường 3, Phường 3, Tây Ninh'),
		('Thái Nguyên','CGV Vincom Thái Nguyên','Tầng 4 , TTTM Vincom Thái Nguyên 286 Lương Ngọc Quyến, Phường Quang Trung, Thành phố Thái Nguyên'),
		('Tiền Giang','CGV GO! Mỹ Tho','Tầng 3, TTTM GO! Mỹ Tho, 545 Lê Văn Phẩm, Phường 5, Thành phố Mỹ Tho, Tiền Giang'),
		('Tiền Giang','CGV Vincom Mỹ Tho','Tầng 5, TTTM Vincom Plaza Mỹ Tho, số 01 A, Đường Hùng Vương, Phường 1, Thành phố Mỹ Tho, Tỉnh Tiền Giang');
		
INSERT INTO food_drink (name, description, price)
VALUES	('CGV Combo', 'Gồm 1 bỏng lớn và 2 nước lớn', 105000),
		('My Combo', 'Gồm 1 bắp vừa và 1 nước lớn', 85000),
		('Golden Combo', 'Combo sự kiện', 179000),
		('Gudetama', 'Combo sự kiện', 179000),
		('Krystal Combo', 'Combo sự kiện', 149000),
		('How to train your dragon combo', 'Combo sự kiện', 169000),
		('Bắp vị ngọt', 'Bắp lẻ', 59000),
		('Bắp vị mặn', 'Bắp lẻ', 59000),
		('Bắp vị caramel', 'Bắp lẻ', 74000),
		('Bắp vị phô mai', 'Bắp lẻ', 74000),
		('Bắp vị chocolate', 'Bắp lẻ', 74000),
		('Nước ngọt tươi', 'Nước lẻ', 38000),
		('Trà sữa đặc biệt', 'Nước lẻ', 35000),
		('Upsize bỏng nước', 'Mỗi lần upsize tốn 2000', 2000),
		('Đổi sang bắp ngọt/mặn', 'Giá đổi vị bỏng', 0),
		('Đổi sang Caramel', 'Giá đổi vị bỏng', 9000),
		('Đổi sang Phô mai', 'Giá đổi vị bỏng', 19000),
		('Đổi sang Chocolate', 'Giá đổi vị bỏng', 15000),
		('Đổi sang Mix Phô mai/Caramel/Chocolate','Giá đổi vị bỏng',9000);
		
INSERT INTO genres (name)
VALUES	('Hành động'),
		('Tội phạm'),
		('Hài'),
		('Hồi hộp'),
		('Tâm lý'),
		('Phiêu lưu'),
		('Thần thoại'),
		('Bí ẩn'),
		('Kinh dị'),
		('Hoạt hình'),
		('Gia đình'),
		('Tình cảm'),
		('Huyền thoại'),
		('Khoa học viễn tưởng');
		
-- get string of genres
CREATE OR REPLACE FUNCTION get_genres(id_genres INTEGER[])
RETURNS character varying AS $$
DECLARE
	_genres character varying;
BEGIN
	SELECT	STRING_AGG(name, ', ')
	INTO	_genres
	FROM	genres
	WHERE	id = ANY(id_genres);
	
	RETURN _genres;
END;
$$ LANGUAGE plpgsql;
		
		
INSERT INTO movies (title, release_date, url_poster, director, actors, genres, duration, age, overview)
VALUES	('FAST AND FURIOUS X',													'2023-05-19', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900175/QLRP/movies/Fast_Furious_aevadm.jpg',									'Louis Leterrier',										'Vin Diesel, Jason Momoa, Brie Larson…',																										'{1, 2}',			'02:21:00', 16,	'Dom Toretto và gia đình của anh ấy bị trở thành mục tiêu của người con trai đầy thù hận của ông trùm ma túy Hernan Reyes.'),
		('LẬT MẶT 6: TẤM VÉ ĐỊNH MỆNH',											'2023-04-28', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900168/QLRP/movies/LatMat6_ytg0sx.jpg',										'Lý Hải',												'Lý Hải, Quốc Cường, Trung Dũng, Huy Khánh, Thanh Thức, Trần Kim Hải, Huỳnh Thi, Diệp Bảo Ngọc, Tú Tri, Quỳnh Như, Tạ Lâm, bé Thùy Linh',		'{3, 1, 4, 5}',	'02:12:00', 16,	'Lật mặt 6 sẽ thuộc thể loại giật gân, tâm lý pha hành động, hài hước.'),
		('VỆ BINH DẢI NGÂN HÀ 3',												'2023-05-03', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900170/QLRP/movies/VeBinhGiaiNganHa3_qtutid.jpg',								'James Gunn',											'Chris Pratt, Zoe Saldana, Dave Bautista',																										'{1, 6, 7}',		'02:29:00', 13,	'Cho dù vũ trụ này có bao la đến đâu, các Vệ Binh của chúng ta cũng không thể trốn chạy mãi mãi. Vệ Binh Dải Ngân Hà 3 dự kiến khởi chiếu tại rạp từ 03.05.2023.'),
		('NHỮNG KẺ THAO TÚNG',													'2023-05-12', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900168/QLRP/movies/NhungKeThaoTung_trnk4d.jpg',								'Robert Rodriguez',										'Ben Affleck, Alice Braga, William Fichtner, JD Pardo',																							'{8, 1, 4}',		'01:33:00', 18,	'Phim theo chân thám tử Daniel Rourke (Ben Affleck) trong hành trình tìm kiếm cô con gái bị mất tích. Anh sớm nhận ra tất cả những chuyện bí ẩn này đều liên quan đến một người đàn ông có sức mạnh thôi miên, bẻ cong thực tại. Với sự hỗ trợ từ nhà ngoại cảm Diana Cruz (Alice Braga), Daniel bắt đầu truy đuổi hắn và phải tìm mọi cách để đưa con gái mình trở về nhà an toàn.'),
		('SISU - GIÀ GÂN BÁO THÙ',												'2023-05-12', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900171/QLRP/movies/SisuGiaGanBaoThu_jocwxy.jpg',								'Jalmari Helander',										'Jorma Tommila, Aksel Hennie, Jack Doolan',																										'{1}',			'01:30:00', 18,	'Lấy bối cảnh năm 1944, SISU kể câu chuyện về một cựu binh phát hiện ra mỏ vàng trong vùng hoang dã của Phần Lan. Trên đường vào thành phố bán vàng, những tên lính Phát Xít tàn bạo đang thực hiện nhiệm vụ tàn phá khắp nơi đã phát hiện ra kho báu và cướp lấy nó từ tay anh ta. Cựu binh quyết tâm đòi lại tất cả, từ nợ cho đến thù, thậm chí nếu điều đó có nghĩa là giết hết tất cả lính Phát Xít.'),
		('QUÁI VẬT ĐEN',														'2023-05-12', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900169/QLRP/movies/QuaiVatDen_p4nnx6.jpg',									'Adrian Grunberg',										'Julio Cesar, Josh Lucas',																														'{1, 4}',			'01:40:00', 16,	'Quái Vật Đen xoay quanh câu chuyện khi kỳ nghỉ bình dị của gia đình Oilman Paul Sturges biến thành cơn ác mộng. Bởi họ đã gặp phải một con cá mập Megalodon hung dữ, không từ bất kỳ khoảnh khắc nào để bảo vệ lãnh thổ của mình. Bị mắc kẹt và tấn công liên tục, Paul và gia đình của mình phải tìm cách để an toàn sống sót trở về bờ trước khi con cá mập khát máu này tấn công lần nữa'),
		('CƠN THỊNH NỘ TỪ CÕI ÂM',												'2023-05-12', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900174/QLRP/movies/ConThinhNoTuCoiAm_zr6rcx.jpg',								'Kevin Lewis',											'Sarah Grey, Meg Foster, Sarah Dumont',																											'{8, 4, 9}',		'01:35:00', 18,	'Câu chuyện bắt đầu khi Elly được gia đình của một người bạn nhờ chăm sóc một người phụ nữ lớn tuổi sống trong một căn nhà gỗ hẻo lánh trong vài ngày. Nhận lời đồng ý, nhưng sau đó Elly phát hiện ra sự xuất hiện của một con quỷ đang ẩn náu trong người phụ nữ chỉ chực chờ để thoát ra. Cùng lúc đó, những bí ẩn về cái chết của mẹ cô dần dần được gợi mở bởi những cơn ác mộng mà Elly phải trải qua.'),
		('REBOUND BẬT BẢNG',													'2023-05-12', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900170/QLRP/movies/ReboundBatBang_kymt5w.jpg',								'Hang-jun Jang',										'Jae-hong Ahn, Jinwoon Jeong, Geon-joo Jung',																									'{5}',			'02:02:00', 0,	'Hành trình kỳ diệu gây chấn động nền bóng rổ trung học vào năm 2012, một người thầy nghiệp dư dẫn dắt 6 cậu học trò tạo nên kỳ tích trong 8 ngày thi đấu liên tục.'),
		('CÔ BÉ CỨU HỎA',														'2023-05-12', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900174/QLRP/movies/CoBeCuuHoa_dnfvof.jpg',									'Laurent Zeitoun, Theodore Ty',							'',																																				'{10}',			'01:32:00', 0,	'Cô Bé Cứu Hoả (tên tiếng Anh: Fireheart) đưa người xem bước vào hành trình 6 kỳ thú của Georgia Nolan - một cô bé thông minh, nhiệt huyết với ước mơ trở thành lính cứu hoả như ba mình. Tuy nhiên, năm 1932 tại New York, phụ nữ không được phép làm công việc này. Nhưng cơ hội “vàng” đã đến khi Georgia nảy ra ý định cải trang thành Joe - một chàng trai vụng về gia nhập đội cứu hoả do chính ba mình thành lập. Vừa phải bảo vệ danh tính thật, vừa phải dấn thân vào phi vụ mạo hiểm: Giải cứu những người lính cứu hoả của thành phố đã lần lượt biến mất trong ngọn lửa bí ẩn thiêu rụi Nhà hát Broadway, liệu Georgia có dũng cảm vượt qua tất cả và thành công?'),
		('CON NHÓT MÓT CHỒNG',													'2023-04-28', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900171/QLRP/movies/ConNhotMotChong_szchtg.jpg',								'Vũ Ngọc Đãng',											'Thái Hòa, Thu Trang, Tiến Luật, NSND Hồng Vân, Huỳnh Phương, Vinh Râu, Thái Vũ',																'{3, 5}',			'01:52:00', 16,	'Lấy cảm hứng từ web drama Chuyện Xóm Tui, phiên bản điện ảnh sẽ mang một màu sắc hoàn toàn khác: hài hước hơn, gần gũi và nhiều cảm xúc hơn Bộ phim là câu chuyện của Nhót - người phụ nữ “chưa kịp già” đã sắp bị mãn kinh, vội vàng đi tìm chồng. Nhưng sâu thẳm trong cô, là khao khát muốn có một đứa con và luôn muốn hàn gắn với người cha suốt ngày say xỉn của mình.'),
		('MÈO SIÊU QUẬY Ở VIỆN BẢO TÀNG',										'2023-04-28', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900169/QLRP/movies/MeoSieuQuayOVienBaoTang_zfugt8.jpg',						'Vasiliy Rovenskiy',									'Anton Eldarov, Polina Gagarina, Aleksandr Gavrilin',																							'{3, 10, 6}',		'01:20:00', 0,	'Câu chuyện xoay quanh tình bạn của chú mèo Vincent và chú chuột Maurice. Vincent vừa nhận được công việc bảo vệ kiệt tác tranh Mona Lisa trong một viện bảo tàng, còn Maurice lại có niềm đam mê gặm nhấm bức tranh này. Mọi chuyện phức tạp hơn khi có người cũng đang nung nấu ý định cướp lấy tuyệt tác Mona Lisa. Liệu Vincent và đồng đội của mình có thể cứu lấy những kiệt tác của Davinci và bảo vệ danh cho bảo tàng không?'),
		('TRẠM TÀU MA',															'2023-04-28', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900175/QLRP/movies/TramTauMa_xv34p9.jpg',										'Jeong Yong Ki',										'Kim Bo Ra, Kim Jae Hyun',																														'{9}',			'01:20:00', 16,	'Lời đồn ma ám về nhà ga Oksu ngày càng nhiều khi những vụ án kinh hoàng liên tục xảy ra. Một đường ray cũ kỹ, một chiếc giếng bỏ hoang, những con số gây ám ảnh hay những vết thương kỳ dị trên thi thể người xấu số... Tất cả dẫn đến một bí mật đau lòng bị chôn vùi nhiều năm trước.'),
		('KHẮC TINH CỦA QUỶ',													'2023-04-14', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900177/QLRP/movies/KhacTinhCuaQuy_vfgw5r.jpg',								'Julius Avery',											'Russell Crowe, Franco Nero',																													'{9}',			'01:44:00', 18,	'Lấy cảm hứng từ những hồ sơ có thật của Cha Gabriele Amorth, Trưởng Trừ Tà của Vatican (Russell Crowe, đoạt giải Oscar®), bộ phim "The Pope''s Exorcist" theo chân Amorth trong cuộc điều tra về vụ quỷ ám kinh hoàng của một cậu bé và dần khám phá ra những bí mật hàng thế kỷ mà Vatican đã cố gắng giấu kín.'),
		('PHIM ANH EM SUPER MARIO',												'2023-04-07', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900169/QLRP/movies/PhimAnhEmSuperMario_vz6v5k.jpg',							'Aaron Horvath, Michael Jelenic',						'Chris Pratt, Anya Taylor-Joy, Charlie Day',																									'{3, 10, 6}',		'01:33:00', 0,	'Câu chuyện về cuộc 6 của anh em Super Mario đến vương quốc Nấm.'),
		('PHIM CÚ ÚP RỔ ĐẦU TIÊN',												'2023-04-14', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900170/QLRP/movies/PhimCuUpRoDauTien_ja615s.jpg',								'Takehiko Inoue, Yasuyuki Ebara',						'Masaya Fukunishi, Yoshiaki Hasegawa, Katsuhisa Hoki, Tetsu Inada, Ryota Iwasaki, Shinichiro Kamio, Mitsuaki Kanuka, Jun Kasama, Subaru Kimura','{3, 10}',		'02:04:00', 13,	'Bộ phim hoạt hình chuyển thể từ loạt truyện tranh “Slam Dunk” nổi tiếng của Takehiko Inoue, khắc họa quá trình trưởng thành cá nhân của những học sinh trung học cống hiến tuổi trẻ cho bóng rổ. Phim theo chân Ryota Miyagi, hậu vệ của đội bóng rổ trường trung học Shohoku. Anh có một người anh trai, Sota, hơn anh ba tuổi và là người đã truyền cảm hứng cho tình yêu bóng rổ của anh. Ryota và các đồng đội của mình là Hanamichi Sakuragi, Takenori Akagi, Hisashi Mitsui và Kaede Rukawa thách đấu nhà vô địch bóng rổ liên trường, đội bóng rổ trường trung học Sannoh. Tác giả nguyên tác Inoue phụ trách chỉ đạo và viết kịch bản.'),
		('NÀNG TIÊN CÁ',														'2023-05-26', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900168/QLRP/movies/NangTienCa_lawsdo.jpg',									'Rob Marshall',											'Halle Bailey, Jonah Hauer-King, Daveed Diggs, Awkwafina, Jacob Tremblay, Noma Dumezweni, Art Malik, with Javier Bardem and Melissa McCarthy',	'{6}',			'00:00:00', 0,	'“Nàng Tiên Cá” là câu chuyện được yêu thích về Ariel - một nàng tiên cá trẻ xinh đẹp và mạnh mẽ với khát khao 6. Ariel là con gái út của Vua Triton và cũng là người ngang ngạnh nhất, nàng khao khát khám phá về thế giới bên kia đại dương. Trong một lần ghé thăm đất liền, nàng đã phải lòng Hoàng tử Eric bảnh bao. Trong khi tiên cá bị cấm tiếp xúc với con người, Ariel đã làm theo trái tim mình. Nàng đã thỏa thuận với phù thủy biển Ursula hung ác để cơ hội sống cuộc sống trên đất liền. Nhưng cuối cùng việc này lại đe dọa tới mạng sống của Ariel và vương miện của cha nàng.'),
		('PHIM ĐIỆN ẢNH DORAEMON: NOBITA VÀ VÙNG ĐẤT LÝ TƯỞNG TRÊN BẦU TRỜI',	'2023-05-26', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900175/QLRP/movies/DoraemonNobitaVaVungDatLyTuongTrenBauTroi_dluez5.jpg',		'Takumi Doyama',										'',																																				'{10}',			'01:48:00', 18,	'Phim điện ảnh Doraemon: Nobita Và Vùng Đất Lý Tưởng Trên Bầu Trời kể câu chuyện khi Nobita tìm thấy một hòn đảo hình lưỡi liềm trên trời mây. Ở nơi đó, tất cả đều hoàn hảo… đến mức cậu nhóc Nobita mê ngủ ngày cũng có thể trở thành một thần đồng toán học, một siêu sao thể thao. Cả hội Doraemon cùng sử dụng một món bảo bối độc đáo chưa từng xuất hiện trước đây để đến với vương quốc tuyệt vời này. Cùng với những người bạn ở đây, đặc biệt là chàng robot mèo Sonya, cả hội đã có chuyến hành trình tới vương quốc trên mây tuyệt vời… cho đến khi những bí mật đằng sau vùng đất lý tưởng này được hé lộ.'),
		('CHÀNG TRAI XINH ĐẸP CỦA TÔI: ĐỜI ĐỜI KIẾP KIẾP',						'2023-05-26', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900174/QLRP/movies/ChangTraiXinhDepCuaToiDoiDoiKiepKiep_ahl3in.jpg',			'Sakai Mai',											'Riku Hagiwara, Yusei Yagi, Akira Takano,…',																									'{12}',			'01:43:00', 18,	'Chuyển thể từ nguyên tác cùng tên trong seri BL light novel của tác giả Nagira Yuu, Chàng Trai Xinh Đẹp Của Tôi nhận được nhiều sự mong đợi của người hâm mộ khi tái xuất với bản điện ảnh My Beautiful Man: Eternal (tên tiếng việt: Chàng Trai Xinh Đẹp Của Tôi: Đời Đời Kiếp Kiếp). Phim kể về mối tình tuyệt đẹp thời học sinh của hai chàng trai Hira và Kiyoi So. Hira vốn là một chàng trai hướng nội lại có tật nói lắp nên đã bị bạn bè bắt nạt. Ngay lúc ấy chàng trai Kiyoi So điển trai đã giúp Hira thoát khỏi cảnh bị bắt nạt. Dần dần cả hai nảy sinh tình cảm và đồng hành cùng nhau suốt những năm tháng thanh xuân. Với bản điện ảnh, người hâm mộ sẽ được theo dõi câu chuyện tiếp nối của bản truyền hình, hứa hẹn sẽ nhẹ nhàng, tươi sáng và đáng yêu. Phim sẽ khởi chiếu tại rạp vào 05.05.2023.'),
		('NGƯỜI NHỆN: DU HÀNH VŨ TRỤ NHỆN',										'2023-06-02', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900945/QLRP/movies/NguoiNhanDuHanhVuTruNhen_op1oyg.jpg',						'Joaquim Dos Santos, Justin K. Thompson, Kemp Powers',	'Shameik Moore',																																'{1, 14, 6}',		'00:00:00', 0,	'Vô số Spider-Man từ khắp các vũ trụ đang đối đầu nhau?! Xem ngay Official Trailer của SPIDER-MAN: ACROSS THE SPIDER-VERSE. Khởi chiếu tại rạp 02.06.2023'),
		('HOON PAYON: BÙA HÌNH NHÂN',											'2023-06-02', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900176/QLRP/movies/HoonPayonBuaHinhNhan_ro9iz6.jpg',							'Mike Phontharis Chotkijsadarsopon',					'Phuwin Tangsakyuen, Up Poompat Iam-samang, Nick Kunatip Pinpradab,…',																			'{9}',			'00:00:00', 0,	'Được lấy cảm hứng từ loại bùa hình nhân hộ mệnh nổi tiếng ở Thái Lan, phim theo chân Tham trong hành trình đến một hòn đảo hẻo lánh để tìm người anh trai của mình đang tu hành ở đó. Tham phát hiện ra anh trai đã bị sát hại sau khi bị buộc tội giết người và trộm cắp. Quyết tâm ở lại hòn đảo để điều tra cũng như minh oan cho anh trai nhưng Tham lại vô tình khám phá ra nhiều cái chết bí ẩn khác tại ngôi làng bên cạnh.'),
		('ÔNG KẸ',																'2023-06-02', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900168/QLRP/movies/OngKe_sqtjcc.jpg',											'Rob Savage',											'Sophie Thatcher, Chris Messina, Vivien Lyra Blair, Marin Ireland, Madison Hu, LisaGay Hamilton, and David Dastmalchian',						'{9}',			'00:00:00', 0,	'Từ nguyên tác truyện ngắn của bậc thầy truyện kinh dị Stephen King, “Ông Kẹ” kể về câu chuyện của gia đình Harper khi một thực thể siêu nhiên bám theo và liên tục phá rối gia đình họ. Khi mà con quái vật này lấp ló trong bóng tối và chực chờ làm hại cô bé Sawyer như chực chờ một con mồi, chị gái Sadie và bố Will sẽ phải hành động để ngăn chặn điều này trước khi quá muộn.'),
		('TRANSFORMERS: QUÁI THÚ TRỖI DẬY',										'2023-06-09', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900172/QLRP/movies/TransformersQuaiThuTroiDay_dchqd0.jpg',					'Steven Caple Jr.',										'Michelle Yeoh, Dominique Fishback, Ron Perlman',																								'{1, 14, 6}',		'00:00:00', 0,	'Bộ phim dựa trên sự kiện Beast Wars trong loạt phim hoạt hình "Transformers", nơi mà các robot có khả năng biến thành động vật khổng lồ cùng chiến đấu chống lại một mối đe dọa tiềm tàng.'),
		('FLASH',																'2023-06-16', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900177/QLRP/movies/Flash_j5fz3o.jpg',											'Andy Muschietti',										'Ben Affleck, Michael Shannon, Michael Keaton',																									'{1, 6, 7}',		'00:00:00', 0,	'Mùa hè này, đa thế giới sẽ va chạm khốc liệt với những bước chạy của FLASH'),
		('XỨ SỞ CÁC NGUYÊN TỐ',													'2023-06-23', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900171/QLRP/movies/XuSoCacNguyenTo_xkne8g.jpg',								'Peter Sohn',											'Leah Lewis, Mamoudou Athie',																													'{11, 3, 10}',	'00:00:00', 0,	'Xứ Sở Các Nguyên Tố từ Disney và Pixar lấy bối cảnh tại thành phố các nguyên tố, nơi lửa, nước, đất và không khí cùng chung sống với nhau. Câu chuyện xoay quanh nhân vật Ember, một cô nàng cá tính, thông minh, mạnh mẽ và đầy sức hút. Tuy nhiên, mối quan hệ của cô với Wade - một anh chàng hài hước, luôn thuận thế đẩy dòng - khiến Ember cảm thấy ngờ vực với thế giới này. Được đạo diễn bởi Peter Sohn, sản xuất bởi Denise Ream, và lồng tiếng bởi Leah Lewis (Ember) và Mamoudou Athie (Wade), phim dự kiến khởi chiếu tại rạp vào tháng 23.06.2023.'),
		('VÚ EM DẠY YÊU',														'2023-06-23', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900172/QLRP/movies/VuEmDayYeu_ugfkgx.jpg',									'Gene Stupnitsky',										'Jennifer Lawrence, Natalie Morales, Ebon Moss-Bachrach',																						'{3}',			'00:00:00', 0,	'Không dành cho bé dưới 18!.. Red Band Trailer với Jennifer Lawrence trở lại, nóng bỏng cả mắt trong tựa phim hài-bựa-lầy nhất hè năm nay #NoHardFeelings - VÚ EM DẠY "YÊU. Duy nhất tại rạp. Dự kiến khởi chiếu 23.06.2023'),
		('INDIANA JONES & VÒNG QUAY ĐỊNH MỆNH',									'2023-06-29', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900177/QLRP/movies/IndianaJonesVongQuayDinhMenh_e8ej1s.jpg',					'James Mangold',										'Boyd Holbrook, Thomas Kretschmann, Mads Mikkelsen, Harrison Ford, Phoebe Waller-Bridge, Shaunette Renée Wilson',								'{1, 6}',			'00:00:00', 0,	'Indiana Jones 5 sẽ pha trộn giữa thực tế, hư cấu khi lấy bối cảnh năm 1969, lần này Indiana Jones sẽ đối mặt với Đức quốc xã trong thời gian diễn ra cuộc chạy đua vào không gian.'),
		('NHIỆM VỤ: BẤT KHẢ THI NGHIỆP BÁO PHẦN MỘT',							'2023-07-14', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900168/QLRP/movies/NhiemVuBatKhaThi_s3l7sh.jpg',								'Christopher McQuarrie',								'Tom Cruise, Rebecca Ferguson, Vanessa Kirby',																									'{1, 6}',			'00:00:00', 0,	'Phần phim thứ 7 của loạt phim Nhiệm Vụ Bất Khả Thi'),
		('DINH THỰ MA ÁM',														'2023-07-28', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900175/QLRP/movies/DinhThuMaAm_j313jo.jpg',									'Justin Simien',										'Jamie Lee Curtis, Owen Wilson, Rosario Dawson',																								'{11, 3, 5}',		'00:00:00', 0,	'Nhà là nơi ma ám. Cùng xem đoạn trailer của bộ phim Dinh Thự Ma Ám sẽ được trình chiếu tại các cụm rạp vào ngày 28.07 này.'),
		('BARBIE',																'2023-07-21', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900172/QLRP/movies/Barbie_lwskpj.jpg',										'Greta Gerwig',											'Margot Robbie, Ryan Gosling, Helen Mirren',																									'{3, 6, 7}',		'00:00:00', 0,	'Bộ phim BARBIE sẽ được nhào nặn và chắp bút bởi nữ đạo diễn kiêm biên kịch từng nhận nhiều Đề cử Tượng vàng Oscar – Greta Grewig. Hai nhân vật chính Barbie và Ken sẽ được hóa thân bởi nữ diên viên Margot Robbie và nam thần Ryan Gosling, hứa hẹn sẽ tạo nên “chemistry” đáng yêu giữa hai nhân vật búp bê nổi tiếng thế giới.'),
		('THIỆN ÁC ĐỐI ĐẦU',													'2023-09-01', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900170/QLRP/movies/ThienAcDoiDau_guqvjj.jpg',									'Antoine Fuqua',										'Denzel Washington, Dakota Fanning, Sonia Ammar, Remo Girone',																					'{1}',			'00:00:00', 0,	'Robert McCall chuyển đến sinh sống tại miền Nam nước Ý nhưng phát hiện ra bạn bè của mình bị một tổ chức mafia ở địa phương kiểm soát. Khi tính mạng của họ bị đe dọa, ông buộc phải quay trở lại con đường sát thủ để bảo vệ bạn bè.'),
		('Án Mạng Ở Venice',													'2023-09-15', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900173/QLRP/movies/AnMangOVenice_owampl.jpg',									'Kenneth Branagh',										'Kelly Reilly, Michelle Yeoh, Kenneth Branagh',																									'{9, 5, 2}',		'00:00:00', 0,	'Dựa trên tiểu thuyết Halloween Party của nhà văn Agatha Christie, hành trình phá án của thám tử Hercule Poirot tiếp tục được đưa lên màn ảnh rộng.'),
		('ĐẤT RỪNG PHƯƠNG NAM',													'2023-10-20', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900174/QLRP/movies/DatRungPhuongNam_fismev.jpg',								'Nguyễn Quang Dũng',									'Hồng Ánh, Huỳnh Hạo Khang, Mai Tài Phến, Công Ninh, Hứa Vĩ Văn, Tuyền Mập, Tuấn Trần',															'{5}',			'00:00:00', 0,	'Sau bao ngày chờ đợi, dự án điện ảnh gợi ký ức tuổi thơ của nhiều thế hệ người Việt chính thức tung hình ảnh đầu tiên đầy cảm xúc. First look poster khắc họa hình ảnh đối lập: bé An đang ôm chặt mẹ giữa một khung cảnh chạy giặc loạn lạc. Cùng chờ đợi và theo dõi thêm hành trình bé An đi tìm cha khắp nam kỳ lục tỉnh cùng các người bạn đồng hành nhé!'),
		('DUNE: HÀNH TINH CÁT - PHẦN HAI',										'2023-11-03', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900175/QLRP/movies/DuneHanhTinhCat2_oumnnp.jpg',								'Denis Villeneuve',										'Denis Villeneuve, Jon Spaihts, Frank Herbert',																									'{1, 6, 5}',		'00:00:00', 13,	'Các chiến binh muôn năm DUNE: HÀNH TINH CÁT - PHẦN HAI dự kiến khởi chiếu tháng 11.2023'),
		('THE MARVELS',															'2023-11-10', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900172/QLRP/movies/TheMarvels_aaulo8.jpg',									'Nia DaCosta',											'Brie Larson, Samuel L. Jackson, Zawe Ashton',																									'{1, 6, 7}',		'00:00:00', 0,	'Phần tiếp theo của Captain Marvel (2019)'),
		('ĐẤU TRƯỜNG SINH TỬ: KHÚC HÁT CỦA CHIM CA VÀ RẮN ĐỘC',					'2023-11-17', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900177/QLRP/movies/DTSTKhucHatCuaChimCaRanDoc_lyvp7d.jpg',					'Francis Lawrence',										'Michael Lesslie, Michael Arndt, Suzanne Collins',																								'{1, 6, 5}',		'00:00:00', 0,	'Thương hiệu phim nổi tiếng Đấu Trường Sinh Tử trở lại với phần tiền truyện mang tên ĐẤU TRƯỜNG SINH TỬ: KHÚC HÁT CỦA CHIM CA VÀ RẮN ĐỘC.'),
		('QUỶ LÙN TINH NGHỊCH: ĐỒNG TÂM HIỆP NHẠC',								'2023-11-17', 'https://res.cloudinary.com/dmez2yyon/image/upload/v1684900170/QLRP/movies/QuyLunTinhNghich_jedzdj.jpg',								'Walt Dohrn, Tim Heitz',								'Anna Kendrick, Zooey Deschanel, Justin Timberlake',																							'{10}',			'00:00:00', 0,	'Cùng chào đón, sự xuất hiện của những chú quỷ lùn mới toanh vừa gia nhập hội');

-- get recommend movies
CREATE OR REPLACE FUNCTION get_recommend_movies(user_id integer)
RETURNS TABLE(id_genres integer[], id_movies integer[])
AS $$
DECLARE
	_genres INTEGER[];
	_movies INTEGER[];
BEGIN
	SELECT	ARRAY_AGG(id)
	INTO	_genres
	FROM   (SELECT	_g.id
			FROM	book _b
					JOIN schedule _s ON _s.id = _b.id_schedule
					JOIN movies _m ON _m.id = _s.id_movie
					JOIN genres _g ON _g.id = ANY(_m.genres)
			WHERE	_b.id_user = user_id
			GROUP BY _g.id
			ORDER BY COUNT(*) DESC
			LIMIT 3) AS subquery;
			
	SELECT	ARRAY_AGG(id)
	INTO	_movies
	FROM   (SELECT	_m.id
			FROM	movies _m
			WHERE	_m.genres && _genres
			LIMIT	3) AS subquery;
	
	RETURN QUERY
	SELECT	_genres, _movies;
END;
$$ LANGUAGE plpgsql;
--SELECT * FROM get_recommend_movies(1)


INSERT INTO rooms (id_cinemas, name, description, surcharge)
VALUES	(ARRAY[13, 8, 12, 15, 19, 4, 1, 3, 2, 9, 10, 17, 61, 51, 60, 50, 57, 47, 48, 62, 59, 46, 54, 28, 22, 32, 26, 27, 52, 53], 'Sweetbox', 'Với nỗ lực không ngừng mang đến cho người yêu phim những trải nghiệm điện ảnh độc đáo, CGV cho ra đời loại ghế đôi SWEETBOX ngọt ngào dành riêng cho các cặp đang yêu.',25000),
		(ARRAY[4, 1, 2, 22], '4DX', '4DX®, một định dạng điện ảnh hoàn toàn mới đánh thức mọi giác quan của khán giả mang đến những trải nghiệm điện ảnh tuyệt đỉnh bằng công nghệ hiện đại nhất trên thế giới.',95000),
		(ARRAY[1, 23], 'Dolby Atmos', 'Dolby Atmos sử dụng thiết kế phân lớp tân tiến để tạo nên các rãnh âm thanh. Lớp nền bao gồm các dải âm thanh môi trường tĩnh được phối theo phương pháp âm thanh phân luồng quen thuộc. Các lớp trên trần bao gồm các yếu tố âm thanh động được định hướng và thay đổi một cách chính xác theo hình ảnh hiển thị trên màn hình trong rạp. Bằng cách lắp đặt hệ thống loa ở trên đầu và xung quanh, Dolby Atmos có thể khiến khán giả trải nghiệm những âm thanh trung thực và tự nhiên như thật của bộ phim.\nLàm thế nào Atmos có thể tạo nên trải nghiệm điện ảnh khác biệt:\n- Âm thanh rõ ràng và được định hướng một cách chính xác hơn; Sự trộn âm có định hướng đối tượng từ các yếu tố âm thanh theo lớp độc lập đến âm thanh phân luồng.\n- Kết nối ý đồ của đạo diễn từ dữ liệu mô tả và phát lại theo công nghệ âm thanh được trang bị cho từng phòng chiếu.\n- Tự động tạo ra các rãnh âm thanh tối ưu cho các phòng chiếu 5.1 và 7.1\n- Tạo ra trải nghiệm âm thanh sống động, trung thực thông qua 128 yếu tố âm thanh đồng thời và không bị mất đi khi phối âm.\n- Quy mô được điều chỉnh theo kích cỡ của từng phòng chiếu với hệ thống lên đến 64 loa độc lập với nhau.',15000),
		(ARRAY[2, 11, 39, 43], 'IMAX', 'IMAX là công nghệ chiếu phim tiên tiến nhất trên thế giới hiện nay, từ thiết kế phòng chiếu vô cùng choáng ngợp đến hiệu ứng âm thanh và hình ảnh đỉnh cao.',65000),
		(ARRAY[4, 1, 13, 18, 27, 26, 48, 32, 30, 11, 35, 54, 43], 'Gold Class', 'Lấy cảm hứng từ ghế ngồi hạng thương gia trên máy bay, phòng chiếu GOLD CLASS ra đời mang đến một không gian xem phim sang trọng và đẳng cấp cho các tín đồ điện ảnh. GOLD CLASS còn là lựa chọn hoàn hảo cho các sự kiện đặc biệt để tạo nên những kỷ niệm tuyệt vời, khó quên.',225000),
		(ARRAY[4, 20, 30, 7, 35, 39, 43], 'L''amour', 'Với mục đích mang đến khoảnh khắc ngọt ngào và cảm giác thoải mái nhất khi xem phim, CGV mang đến phòng chiếu giường nằm L’amour với thiết kế nội thất sang trọng bậc nhất trong hệ thống rạp CGV hứa hẹn trải nghiệm tuyệt vời cho khán giả.',525000),
		(ARRAY[10, 17, 4, 5, 53], 'Starium', 'STARIUM là công nghệ chiếu phim do chính CGV sáng tạo ra để những trải nghiệm của khán giả vượt xa cả giới hạn chân thực.',10000),
		(ARRAY[18], 'Premium Cinema', 'Không gian đậm chất điện ảnh với ghế ngồi được di chuyển theo yêu cầu của riêng bạn',5000),
		(ARRAY[32, 1], 'Screen X', 'ScreenX vượt qua khuôn khổ giới hạn của màn hình chính và phóng đại không gian hình ảnh sang hai bên tường đến tận hàng ghế cuối cùng.',45000),
		(ARRAY[42, 53], 'Cine & Forêt', 'Lấy cảm hứng từ rừng rậm nhiệt đới với 3 tông màu chủ đạo: Xanh - Cam - Vàng, phòng chiếu Cine & Forêt ra đời, mang đến không gian xanh mát trong hành trình thưởng thức điện ảnh của những ai mê phim. Cine & Forêt chính là sự lựa chọn của ai muốn tìm kiếm trải nghiệm mới lạ, hòa mình cùng thiên nhiên.',5000),
		(ARRAY[7], 'Cine & Living', 'Rạp chiếu phim Cine & Living theo phong cách phòng khách sang trọng với màn hình LED ONYX sắc nét mang trải nghiệm điện ảnh sống động tối đa trong từng khoảnh khắc.',5000),
		(ARRAY[2, 53], 'Cine & Suit', 'Với 3 tông màu chủ đạo: Xanh - Xám - Vàng, phòng chiếu Cine & Suite ra đời, mang đến không gian sang trọng trong hành trình thưởng thức điện ảnh của những tín đồ mê phim. Cine & Suite chính là sự lựa chọn của ai muốn tìm kiếm trải nghiệm mới lạ, sang trọng và thoải mái.',5000),
		(ARRAY[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83], 'Rạp 2D', 'Phòng số 1',0),
		(ARRAY[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83], 'Rạp 2D', 'Phòng số 2',0),
		(ARRAY[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83], 'Rạp 2D', 'Phòng số 3',0),
		(ARRAY[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83], 'Rạp 2D', 'Phòng số 4',0);

------ About schedule ------
CREATE OR REPLACE PROCEDURE generate_schedule (
	p_id_movie	INTEGER,
	p_date		date
)
AS $$
BEGIN
	IF	NOT EXISTS (SELECT *
				   FROM schedule
				   WHERE id_movie = p_id_movie AND date = p_date)
		AND p_date < CURRENT_DATE + 3
	THEN
		INSERT INTO schedule (id_movie, id_cinema, id_room, date, time)
		VALUES	(p_id_movie,'1','13',p_date,ARRAY['08:00:00','09:00:00','09:25:00','10:30:00','10:55:00','11:50:00','12:15:00','13:20:00','13:45:00','14:40:00','15:05:00','16:35:00','17:30:00','17:55:00','19:00:00','19:25:00','20:20:00','20:45:00','21:50:00','22:15:00','23:10:00','23:35:00']::time[]),
				(p_id_movie,'1','5',p_date,ARRAY['10:10:00','13:00:00','15:50:00','18:40:00','21:30:00']::time[]),
				(p_id_movie,'3','13',p_date,ARRAY['09:20:00','10:00:00','10:45:00','11:25:00','12:05:00','13:30:00','14:10:00','14:50:00','15:30:00','16:15:00','16:55:00','17:35:00','19:00:00','19:40:00','20:20:00','21:00:00','21:50:00','22:30:00','23:05:00','23:30:00']::time[]),
				(p_id_movie,'7','13',p_date,ARRAY['09:00:00','09:30:00','12:00:00','12:20:00','13:45:00','14:15:00','14:45:00','16:30:00','17:00:00','17:30:00','18:00:00','19:20:00','20:15:00','22:10:00','22:40:00','23:00:00']::time[]),
				(p_id_movie,'7','6',p_date,ARRAY['10:15:00','13:00:00','15:50:00','18:40:00','21:30:00']::time[]),
				(p_id_movie,'9','13',p_date,ARRAY['08:30:00','09:10:00','09:30:00','09:50:00','10:10:00','10:50:00','11:20:00','12:00:00','12:20:00','12:40:00','13:40:00','14:10:00','14:50:00','15:10:00','15:30:00','16:00:00','16:30:00','17:00:00','18:00:00','18:30:00','19:20:00','19:50:00','20:30:00','20:50:00','21:20:00','21:50:00','22:10:00','22:40:00','23:00:00','23:20:00']::time[]),
				(p_id_movie,'14','13',p_date,ARRAY['08:00:00','08:50:00','09:20:00','10:00:00','10:20:00','10:50:00','11:40:00','12:50:00','13:10:00','13:40:00','14:30:00','15:00:00','15:40:00','16:00:00','16:30:00','17:30:00','17:50:00','18:30:00','18:50:00','19:20:00','20:20:00','20:40:00','21:20:00','21:40:00','22:10:00']::time[]),
				(p_id_movie,'12','13',p_date,ARRAY['09:00:00','10:00:00','11:00:00','11:30:00','12:00:00','13:00:00','14:00:00','14:30:00','15:00:00','16:00:00','17:00:00','17:30:00','18:00:00','19:00:00','20:00:00','20:30:00','21:00:00','22:00:00']::time[]),
				(p_id_movie,'13','13',p_date,ARRAY['08:55:00','11:40:00','14:30:00','15:00:00','17:20:00','17:50:00','19:10:00','20:10:00','20:35:00','21:55:00','23:00:00','23:20:00']::time[]),
				(p_id_movie,'13','5',p_date,ARRAY['09:50:00','12:40:00','15:30:00','18:20:00','21:05:00','23:55:00']::time[]),
				(p_id_movie,'13','1',p_date,ARRAY['11:10:00','14:00:00','16:50:00','19:40:00','22:30:00']::time[]),
				(p_id_movie,'17','13',p_date,ARRAY['09:00:00','09:45:00','12:00:00','12:45:00','15:00:00','15:45:00','18:00:00','18:45:00','21:00:00','21:40:00']::time[]),
				(p_id_movie,'17','7',p_date,ARRAY['10:20:00','13:20:00','16:20:00','19:20:00','22:15:00']::time[]),
				(p_id_movie,'2','13',p_date,ARRAY['09:00:00','11:00:00','11:30:00','13:50:00','14:20:00','16:40:00','17:10:00','19:30:00','20:00:00','22:20:00','22:50:00']::time[]),
				(p_id_movie,'2','12',p_date,ARRAY['10:00:00','12:50:00','15:40:00','18:30:00','21:20:00']::time[]),
				(p_id_movie,'8','13',p_date,ARRAY['09:15:00','10:15:00','10:45:00','11:15:00','11:45:00','12:15:00','13:15:00','13:45:00','14:45:00','15:15:00','16:15:00','16:45:00','17:15:00','17:45:00','18:15:00','19:15:00','19:45:00','20:45:00','21:15:00','22:15:00','22:45:00']::time[]),
				(p_id_movie,'19','13',p_date,ARRAY['08:50:00','09:30:00','10:30:00','11:00:00','11:40:00','12:20:00','13:20:00','13:50:00','14:30:00','15:10:00','16:10:00','16:40:00','17:20:00','18:00:00','19:00:00','19:30:00','20:10:00','20:50:00','21:50:00','22:20:00','23:00:00','23:40:00']::time[]),
				(p_id_movie,'4','13',p_date,ARRAY['09:40:00','12:25:00','15:10:00','17:55:00','20:40:00','21:45:00','23:25:00']::time[]),
				(p_id_movie,'4','7',p_date,ARRAY['09:00:00','11:45:00','14:30:00','17:15:00','20:00:00','22:50:00']::time[]),
				(p_id_movie,'4','6',p_date,ARRAY['10:20:00','13:05:00','15:50:00','18:35:00','21:20:00']::time[]),
				(p_id_movie,'10','13',p_date,ARRAY['08:40:00','09:20:00','10:05:00','10:45:00','11:25:00','11:45:00','12:50:00','13:30:00','14:10:00','14:30:00','14:50:00','15:35:00','16:15:00','16:55:00','17:15:00','18:05:00','18:25:00','19:00:00','19:40:00','20:00:00','20:20:00','20:50:00','21:15:00','21:45:00','22:25:00','22:45:00','23:05:00']::time[]),
				(p_id_movie,'18','13',p_date,ARRAY['09:40:00','10:15:00','11:20:00','12:30:00','13:10:00','14:10:00','14:30:00','15:20:00','16:00:00','17:00:00','17:20:00','18:10:00','19:00:00','19:15:00','20:10:00','21:00:00','21:50:00','22:10:00','22:40:00','23:00:00']::time[]),
				(p_id_movie,'18','5',p_date,ARRAY['11:00:00','13:50:00','16:40:00','19:30:00','22:20:00']::time[]),
				(p_id_movie,'18','8',p_date,ARRAY['12:00:00','14:50:00','17:40:00','20:30:00']::time[]),
				(p_id_movie,'15','13',p_date,ARRAY['09:00:00','09:50:00','10:30:00','11:50:00','12:40:00','13:20:00','13:50:00','14:40:00','15:30:00','16:10:00','17:30:00','18:20:00','19:00:00','19:40:00','20:20:00','21:10:00','21:50:00']::time[]),
				(p_id_movie,'20','13',p_date,ARRAY['10:30:00','11:15:00','12:15:00','13:15:00','14:00:00','15:00:00','16:00:00','16:45:00','17:45:00','18:45:00','19:30:00','20:30:00','21:30:00','22:15:00','23:15:00']::time[]),
				(p_id_movie,'20','6',p_date,ARRAY['12:45:00','15:30:00','18:15:00','21:00:00']::time[]),
				(p_id_movie,'5','13',p_date,ARRAY['09:20:00','09:50:00','10:20:00','12:10:00','12:40:00','13:20:00','13:50:00','14:50:00','15:10:00','15:40:00','16:20:00','16:50:00','17:50:00','18:10:00','18:40:00','19:10:00','19:30:00','19:50:00','20:40:00','21:00:00','21:30:00','22:00:00','22:40:00']::time[]),
				(p_id_movie,'5','7',p_date,ARRAY['08:50:00','11:40:00','14:30:00','17:30:00','20:20:00']::time[]),
				(p_id_movie,'11','13',p_date,ARRAY['09:20:00','11:40:00','12:10:00','12:40:00','14:30:00','15:00:00','17:20:00','17:50:00','18:30:00','20:10:00','20:40:00','21:10:00','23:00:00','23:30:00']::time[]),
				(p_id_movie,'11','5',p_date,ARRAY['10:20:00','13:10:00','16:10:00','19:10:00','22:10:00']::time[]),
				(p_id_movie,'16','13',p_date,ARRAY['09:30:00','10:30:00','11:00:00','12:10:00','13:10:00','13:40:00','14:50:00','16:20:00','17:30:00','18:00:00','18:30:00','19:00:00','20:10:00','21:15:00','21:40:00']::time[]),
				(p_id_movie,'21','13',p_date,ARRAY['08:50:00','09:30:00','10:00:00','10:30:00','10:50:00','11:20:00','11:45:00','12:20:00','12:50:00','13:20:00','13:45:00','14:10:00','14:40:00','15:10:00','15:40:00','16:10:00','16:40:00','17:00:00','17:30:00','18:00:00','18:30:00','19:00:00','19:30:00','20:20:00','20:50:00','21:20:00','21:50:00','22:20:00','22:40:00','23:10:00']::time[]),
				(p_id_movie,'6','13',p_date,ARRAY['09:20:00','10:00:00','10:30:00','11:00:00','11:30:00','12:00:00','12:40:00','13:10:00','13:40:00','14:10:00','14:40:00','15:20:00','15:50:00','16:20:00','16:50:00','17:20:00','18:00:00','18:30:00','19:00:00','19:30:00','20:00:00','20:40:00','21:10:00','21:40:00','22:10:00','22:40:00','23:20:00']::time[]),
				(p_id_movie,'2','4',p_date,ARRAY['10:30:00','13:20:00','16:10:00','19:00:00','21:50:00']::time[]),
				(p_id_movie,'11','4',p_date,ARRAY['10:50:00','13:40:00','16:40:00','19:40:00','22:40:00']::time[]),
				(p_id_movie,'1','2',p_date,ARRAY['08:30:00','11:20:00','14:10:00','17:00:00','19:50:00','22:40:00']::time[]),
				(p_id_movie,'2','2',p_date,ARRAY['09:30:00','12:15:00','15:00:00','17:45:00','20:30:00']::time[]),
				(p_id_movie,'4','2',p_date,ARRAY['11:00:00','13:50:00','16:35:00','19:20:00','22:10:00']::time[]),
				(p_id_movie,'1','9',p_date,ARRAY['09:50:00','12:40:00','15:30:00','18:20:00','21:10:00']::time[]),
				(p_id_movie,'22','13',p_date,ARRAY['09:10:00','09:40:00','10:20:00','11:00:00','11:35:00','12:00:00','12:30:00','13:20:00','14:00:00','14:50:00','15:20:00','16:20:00','17:00:00','17:40:00','18:10:00','18:30:00','19:15:00','19:45:00','20:00:00','20:20:00','20:30:00','21:00:00','21:20:00','21:45:00','22:10:00','22:40:00','23:00:00']::time[]),
				(p_id_movie,'23','13',p_date,ARRAY['10:10:00','10:55:00','11:30:00','12:30:00','13:00:00','13:45:00','14:20:00','15:20:00','15:50:00','16:35:00','17:10:00','18:10:00','18:40:00','19:25:00','20:00:00','21:00:00','21:30:00','22:15:00','22:50:00']::time[]),
				(p_id_movie,'24','13',p_date,ARRAY['10:15:00','11:15:00','12:15:00','13:15:00','14:00:00','16:00:00','17:00:00','17:45:00','18:15:00','18:45:00','19:30:00','20:00:00','21:00:00','21:30:00','22:15:00','22:50:00']::time[]),
				(p_id_movie,'25','13',p_date,ARRAY['08:35:00','09:25:00','09:50:00','11:10:00','11:35:00','12:25:00','14:10:00','14:35:00','16:45:00','17:10:00','17:35:00','18:25:00','18:50:00','19:15:00','20:10:00','20:35:00','21:25:00','21:50:00','22:15:00','22:45:00','23:10:00']::time[]),
				(p_id_movie,'26','13',p_date,ARRAY['10:10:00','10:50:00','11:25:00','12:10:00','13:10:00','13:45:00','14:20:00','15:00:00','16:05:00','16:40:00','17:15:00','17:50:00','19:00:00','19:35:00','20:10:00','20:40:00','21:50:00','22:30:00','23:00:00','23:20:00']::time[]),
				(p_id_movie,'26','5',p_date,ARRAY['09:45:00','12:40:00','15:30:00','18:20:00','21:15:00']::time[]),
				(p_id_movie,'27','13',p_date,ARRAY['09:30:00','10:20:00','11:10:00','11:30:00','11:55:00','12:20:00','13:20:00','14:00:00','14:20:00','14:45:00','15:10:00','16:10:00','17:10:00','17:35:00','18:00:00','18:30:00','18:45:00','20:00:00','20:25:00','20:50:00','21:20:00','21:35:00','21:50:00','22:50:00','23:15:00']::time[]),
				(p_id_movie,'28','13',p_date,ARRAY['10:00:00','12:15:00','13:40:00','13:55:00','15:10:00','15:45:00','17:00:00','18:50:00','20:00:00','20:15:00','21:10:00','21:40:00','22:20:00','23:00:00']::time[]),
				(p_id_movie,'29','13',p_date,ARRAY['10:00:00','11:15:00','11:45:00','13:30:00','15:40:00','16:15:00','17:15:00','19:00:00','19:30:00','20:00:00','20:30:00','21:45:00','22:45:00']::time[]),
				(p_id_movie,'35','13',p_date,ARRAY['10:00:00','10:30:00','12:00:00','13:00:00','15:00:00','16:00:00','18:00:00','18:30:00','19:00:00','21:00:00','21:30:00','22:00:00']::time[]),
				(p_id_movie,'35','5',p_date,ARRAY['11:00:00','14:00:00','17:00:00','20:00:00']::time[]),
				(p_id_movie,'35','6',p_date,ARRAY['13:30:00','16:35:00','19:40:00']::time[]),
				(p_id_movie,'34','13',p_date,ARRAY['10:00:00','10:45:00','11:15:00','12:45:00','13:30:00','14:00:00','14:30:00','15:30:00','16:15:00','16:45:00','17:15:00','18:15:00','19:00:00','19:30:00','21:00:00','21:45:00','22:15:00','22:45:00']::time[]),
				(p_id_movie,'30','13',p_date,ARRAY['10:00:00','10:40:00','11:30:00','11:50:00','12:50:00','13:30:00','14:20:00','15:20:00','15:40:00','16:20:00','17:10:00','17:40:00','18:30:00','19:10:00','20:00:00','20:30:00','21:00:00','21:20:00','22:00:00','22:50:00']::time[]),
				(p_id_movie,'31','13',p_date,ARRAY['10:15:00','10:30:00','11:10:00','11:25:00','12:15:00','13:15:00','13:30:00','14:05:00','14:20:00','15:15:00','16:10:00','16:25:00','17:00:00','17:10:00','18:15:00','18:45:00','19:05:00','19:15:00','19:50:00','20:00:00','21:15:00','21:45:00','22:00:00','22:10:00','22:25:00','22:50:00']::time[]),
				(p_id_movie,'31','8',p_date,ARRAY['10:55:00','13:50:00','16:45:00','19:40:00','22:35:00']::time[]),
				(p_id_movie,'32','13',p_date,ARRAY['10:00:00','12:45:00','14:25:00','15:30:00','18:15:00','21:00:00','22:00:00']::time[]),
				(p_id_movie,'32','5',p_date,ARRAY['17:15:00','20:00:00']::time[]),
				(p_id_movie,'33','13',p_date,ARRAY['10:00:00','10:30:00','11:00:00','11:45:00','12:15:00','12:45:00','13:15:00','13:45:00','14:30:00','15:00:00','15:30:00','16:00:00','16:30:00','17:15:00','17:45:00','18:15:00','18:45:00','19:15:00','20:00:00','20:30:00','21:00:00','21:30:00','22:00:00','22:45:00']::time[]),
				(p_id_movie,'36','13',p_date,ARRAY['09:00:00','09:40:00','11:45:00','12:25:00','13:15:00','14:35:00','16:55:00','17:25:00','18:55:00','19:45:00','20:10:00','21:40:00','22:30:00','22:55:00']::time[]),
				(p_id_movie,'37','13',p_date,ARRAY['10:30:00','11:00:00','12:20:00','12:50:00','13:20:00','13:50:00','14:45:00','15:10:00','15:40:00','16:10:00','16:40:00','17:30:00','18:00:00','18:30:00','19:00:00','19:30:00','20:10:00','21:00:00','21:30:00','22:00:00','22:25:00','22:45:00','23:10:00']::time[]),
				(p_id_movie,'39','13',p_date,ARRAY['10:40:00','12:20:00','13:30:00','15:10:00','16:20:00','18:00:00','19:10:00','20:50:00','21:10:00','22:00:00']::time[]),
				(p_id_movie,'39','6',p_date,ARRAY['11:50:00','14:40:00','17:30:00','20:20:00','23:10:00']::time[]),
				(p_id_movie,'38','13',p_date,ARRAY['10:00:00','10:45:00','11:15:00','11:45:00','12:40:00','14:00:00','14:30:00','15:00:00','15:20:00','16:15:00','16:45:00','17:15:00','17:45:00','18:00:00','19:00:00','19:30:00','20:00:00','20:45:00','22:45:00','23:05:00']::time[]),
				(p_id_movie,'40','13',p_date,ARRAY['09:00:00','09:25:00','10:20:00','10:50:00','11:20:00','11:50:00','12:15:00','13:10:00','13:40:00','14:10:00','15:05:00','16:00:00','16:30:00','17:00:00','17:55:00','18:20:00','18:50:00','19:20:00','19:50:00','20:45:00','21:10:00','21:40:00','22:10:00','22:40:00','23:10:00']::time[]),
				(p_id_movie,'41','13',p_date,ARRAY['10:30:00','11:30:00','13:20:00','13:50:00','16:10:00','17:10:00','19:00:00','20:20:00','22:25:00','22:45:00','23:00:00']::time[]),
				(p_id_movie,'42','13',p_date,ARRAY['10:10:00','10:40:00','11:00:00','12:00:00','13:00:00','13:30:00','13:50:00','14:50:00','15:50:00','16:20:00','16:40:00','17:40:00','18:40:00','19:10:00','19:30:00','20:10:00','21:30:00','22:00:00','22:20:00','23:00:00','23:20:00']::time[]),
				(p_id_movie,'43','13',p_date,ARRAY['10:05:00','10:30:00','12:00:00','13:00:00','15:00:00','16:00:00','18:00:00','19:00:00','20:10:00','21:00:00','21:15:00','22:00:00','23:10:00']::time[]),
				(p_id_movie,'43','6',p_date,ARRAY['11:30:00','14:30:00','17:30:00','20:20:00','23:10:00']::time[]),
				(p_id_movie,'44','13',p_date,ARRAY['09:55:00','10:55:00','11:55:00','12:45:00','13:45:00','14:40:00','15:30:00','16:30:00','17:25:00','18:15:00','19:15:00','20:10:00','21:00:00','22:00:00','22:55:00']::time[]),		
				(p_id_movie,'27','5',p_date,ARRAY['10:50:00','13:40:00','16:30:00','19:20:00','22:10:00']::time[]),
				(p_id_movie,'30','5',p_date,ARRAY['10:20:00','13:10:00','16:00:00','18:50:00','21:40:00']::time[]),
				(p_id_movie,'42','10',p_date,ARRAY['11:20:00','14:10:00','17:00:00','19:50:00','22:40:00']::time[]),
				(p_id_movie,'30','6',p_date,ARRAY['11:10:00','14:00:00','16:50:00','19:40:00','22:30:00']::time[]),
				(p_id_movie,'39','4',p_date,ARRAY['11:20:00','14:10:00','17:00:00','19:50:00','22:40:00']::time[]),
				(p_id_movie,'43','4',p_date,ARRAY['11:00:00','14:00:00','17:00:00','20:00:00','23:00:00']::time[]),
				(p_id_movie,'22','2',p_date,ARRAY['10:00:00','13:00:00','16:00:00','19:00:00','21:50:00']::time[]);
				
		UPDATE schedule SET id_room = (FLOOR(RANDOM() * 4) + 13)::INTEGER WHERE id_room = 13;
	END IF;
END;
$$ LANGUAGE plpgsql;
-- CALL generate_schedule(1, '2023-05-24');

CREATE OR REPLACE FUNCTION update_schedule(f_id_movie INTEGER, f_id_cinema INTEGER, f_id_room INTEGER, f_date DATE, f_time TIME WITHOUT TIME ZONE[])
RETURNS TEXT AS $$
BEGIN
	IF EXISTS (SELECT * FROM schedule WHERE id_cinema = f_id_cinema AND id_room = f_id_room AND date = f_date) THEN
		IF EXISTS (SELECT * FROM schedule WHERE id_cinema = f_id_cinema AND id_room = f_id_room AND date = f_date AND time && f_time) THEN
			RETURN 'Fail!';
		ELSE
			UPDATE	schedule
			SET		time = time || f_time
			WHERE	id_movie = f_id_movie
					AND id_cinema = f_id_cinema
					AND id_room = f_id_room
					AND date = f_date;
		END IF;
	ELSE 
		INSERT INTO schedule(id_movie, id_cinema, id_room, date, time)
		VALUES (f_id_movie, f_id_cinema, f_id_room, f_date, f_time);
	END IF;

	RETURN 'Success!';
END;
$$ LANGUAGE plpgsql;
-- SELECT update_schedule(1, 1, 1, '2023-05-25', '{21:06:06, 02:02:27}') AS status

------ About seats ------
CREATE OR REPLACE PROCEDURE get_seat (
	p_id_schedule	INTEGER,
    p_time			TIME WITHOUT TIME ZONE
)
AS $$
DECLARE
	i INTEGER;
	rows_of_seat INTEGER[];
	booked_seats INTEGER[];
	start_seat INTEGER;
	number_of_seats INTEGER;
BEGIN
	IF NOT EXISTS (SELECT *
				   FROM seats
				   WHERE id_seat = 1 AND id_schedule = p_id_schedule AND time = p_time)
	THEN
		INSERT INTO seats (id_seat, id_schedule, time, status)
		SELECT generate_series(1, 300), p_id_schedule, p_time, 0;
		
		UPDATE	seats
		SET		status = -1
		WHERE	id_seat IN (1, 2, 3, 19, 20, 21, 22, 41, 42, 61, 62, 81, 82, 101, 102, 121, 122, 141, 142)
				AND id_schedule = p_id_schedule
				AND time = p_time;
			
		---- Add booked seats	
		-- Get rows of booked seats
		SELECT ARRAY_AGG(DISTINCT (FLOOR(RANDOM() * 6) + 6) * 20)
		INTO rows_of_seat
		FROM generate_series(1, 4);
		
		-- Generate id booked seats
		FOR i IN 1..array_length(rows_of_seat, 1) LOOP
			SELECT FLOOR(RANDOM() * 11) + 7 INTO start_seat;
			SELECT FLOOR(RANDOM() * 2) + 2 INTO number_of_seats;

			booked_seats := booked_seats || ARRAY(SELECT generate_series(rows_of_seat[i] + start_seat, rows_of_seat[i] + start_seat + number_of_seats - 1));
		END LOOP;
		
		-- Update seats
		UPDATE	seats
		SET		status = 1
		WHERE	id_seat = ANY(booked_seats)
				AND id_schedule = p_id_schedule
				AND time = p_time;
	END IF;
END;
$$ LANGUAGE plpgsql;

-- CALL get_seat(1, '09:00:00');
-- SELECT * FROM seats

-- set seat to reserved / sold
-- UPDATE seats SET status = 1 WHERE id_seat = 1 AND id_schedule = 1 RETURNING *;

-- set seat to unavailable
-- UPDATE seats SET status = -1 WHERE id_seat = 1 AND id_schedule = 1 RETURNING *;

-- init shifts for all cinemas
DO $$
BEGIN
	FOR i IN 1..83 LOOP
		INSERT INTO shifts (id_cinema, day, time_start, time_end, id_staffs)
		VALUES	(i, 'Monday', '07:00:00', '12:00:00', ARRAY[]::integer[]),
				(i, 'Monday', '12:00:00', '17:00:00', ARRAY[]::integer[]),
				(i, 'Monday', '17:00:00', '22:00:00', ARRAY[]::integer[]),
				(i, 'Tuesday', '07:00:00', '12:00:00', ARRAY[]::integer[]),
				(i, 'Tuesday', '12:00:00', '17:00:00', ARRAY[]::integer[]),
				(i, 'Tuesday', '17:00:00', '22:00:00', ARRAY[]::integer[]),
				(i, 'Wednesday', '07:00:00', '12:00:00', ARRAY[]::integer[]),
				(i, 'Wednesday', '12:00:00', '17:00:00', ARRAY[]::integer[]),
				(i, 'Wednesday', '17:00:00', '22:00:00', ARRAY[]::integer[]),
				(i, 'Thursday', '07:00:00', '12:00:00', ARRAY[]::integer[]),
				(i, 'Thursday', '12:00:00', '17:00:00', ARRAY[]::integer[]),
				(i, 'Thursday', '17:00:00', '22:00:00', ARRAY[]::integer[]),
				(i, 'Friday', '07:00:00', '12:00:00', ARRAY[]::integer[]),
				(i, 'Friday', '12:00:00', '17:00:00', ARRAY[]::integer[]),
				(i, 'Friday', '17:00:00', '22:00:00', ARRAY[]::integer[]),
				(i, 'Saturday', '07:00:00', '12:00:00', ARRAY[]::integer[]),
				(i, 'Saturday', '12:00:00', '17:00:00', ARRAY[]::integer[]),
				(i, 'Saturday', '17:00:00', '22:00:00', ARRAY[]::integer[]),
				(i, 'Sunday', '07:00:00', '12:00:00', ARRAY[]::integer[]),
				(i, 'Sunday', '12:00:00', '17:00:00', ARRAY[]::integer[]),
				(i, 'Sunday', '17:00:00', '22:00:00', ARRAY[]::integer[]);
	END LOOP;
END $$;

-- insert an staff's account admin
INSERT INTO users (name, phone, email, password, dob, gender, is_staff)
VALUES ('Admin', '0123456789', 'admin@gmail.com', '$2b$11$gq1nDLTT350Wb6iY8wXfRuKYMvx7apsAvzBBagfYdXun1u.oJIsBS', '2002-01-01', 'male', true);

------ About tickets ------	
-- function to calculate original price of ticket
CREATE OR REPLACE FUNCTION original_price(
	_date date,
	_time time without time zone,
	_age integer
)
RETURNS real AS $$
DECLARE
	_dow numeric := EXTRACT(DOW FROM _date::date);
BEGIN
	IF _dow IN (1, 2, 4) THEN
		IF _age > 15 THEN
			IF _time < '12:00:00' THEN
				RETURN 70000;
			ELSE
				RETURN 85000;
			END IF;
		ELSE
			RETURN 60000;
		END IF;
	ELSEIF _dow IN (5, 6, 7) THEN
		IF _age > 15 THEN
			RETURN 105000;
		ELSE
			RETURN 70000;
		END IF;
	ELSE
		RETURN 75000;
	END IF;
END;
$$ LANGUAGE plpgsql;

-- function to calculate real ticket's price 
CREATE OR REPLACE FUNCTION real_price(
	_date date,
	_time time without time zone,
	_user_dob date,
	_id_room integer
)
RETURNS real AS $$
DECLARE
	price numeric;
BEGIN
	SELECT	original_price(_date, _time, DATE_PART('year', age(_user_dob))::integer) + surcharge INTO price
	FROM	rooms
	WHERE	id = _id_room;
	
	RETURN price;
END;
$$ LANGUAGE plpgsql;

-- get price of ticket by date, time, age and type (id) of room
-- SELECT real_price('2023-05-27', '09:30:00', '2002-01-01', 1) AS price

END;